Update to handle new interface for XSLException
git-svn-id: https://svn.apache.org/repos/asf/xml/security/trunk@351099 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/c/src/configure b/c/src/configure
--- a/c/src/configure
+++ b/c/src/configure
@@ -3913,6 +3913,65 @@ _ACEOF
 
 fi
 
+
+# Check for handling of XSLException types
+if test "$xalan_found" = "yes" ; then
+
+  echo "$as_me:$LINENO: checking XSLException::getType() returns XalanDOMString" >&5
+echo $ECHO_N "checking XSLException::getType() returns XalanDOMString... $ECHO_C" >&6
+
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <xalanc/PlatformSupport/XSLException.hpp>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+ try {
+          int x = 1;
+      }
+      catch (XALAN_CPP_NAMESPACE_QUALIFIER XSLException &e) {
+        e.getType().c_str();
+      }
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cat >>confdefs.h <<\_ACEOF
+#define XSEC_XSLEXCEPTION_RETURNS_DOMSTRING 1
+_ACEOF
+
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext;
+
+fi
+
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
