Fix to compile against OpenSSL 0.9.6
git-svn-id: https://svn.apache.org/repos/asf/xml/security/trunk@351372 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/c/src/configure b/c/src/configure
--- a/c/src/configure
+++ b/c/src/configure
@@ -5349,6 +5349,70 @@ _ACEOF
 fi
 
 
+echo "$as_me:$LINENO: checking whether CRYPTO_cleanup_all_ex_data is declared" >&5
+echo $ECHO_N "checking whether CRYPTO_cleanup_all_ex_data is declared... $ECHO_C" >&6
+if test "${ac_cv_have_decl_CRYPTO_cleanup_all_ex_data+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <openssl/crypto.h>
+
+int
+main ()
+{
+#ifndef CRYPTO_cleanup_all_ex_data
+  char *p = (char *) CRYPTO_cleanup_all_ex_data;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_have_decl_CRYPTO_cleanup_all_ex_data=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_have_decl_CRYPTO_cleanup_all_ex_data=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_decl_CRYPTO_cleanup_all_ex_data" >&5
+echo "${ECHO_T}$ac_cv_have_decl_CRYPTO_cleanup_all_ex_data" >&6
+if test $ac_cv_have_decl_CRYPTO_cleanup_all_ex_data = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define XSEC_OPENSSL_HAVE_CRYPTO_CLEANUP_ALL_EX_DATA 1
+_ACEOF
+
+fi
+
+
 echo "$as_me:$LINENO: checking for const input buffer in loadX509Base64Bin" >&5
 echo $ECHO_N "checking for const input buffer in loadX509Base64Bin... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
