Compile against OpenSSL 0.9.6x
git-svn-id: https://svn.apache.org/repos/asf/xml/security/trunk@350965 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/c/src/configure b/c/src/configure
--- a/c/src/configure
+++ b/c/src/configure
@@ -4082,8 +4082,8 @@ if test $ac_cv_lib_crypto_EVP_DecryptInit = yes; then
   openssllib_found=yes
 else
   LIBS=$OLD_LIBS
-	  { { echo "$as_me:$LINENO: error: \"Unable to find libcrypto in OPENSSL\"" >&5
-echo "$as_me: error: \"Unable to find libcrypto in OPENSSL\"" >&2;}
+	  { { echo "$as_me:$LINENO: error: \"Unable to find libcrypto\"" >&5
+echo "$as_me: error: \"Unable to find libcrypto\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -4138,6 +4138,189 @@ fi
 rm -f conftest.err conftest.$ac_ext;
 
 fi
+
+# Now try to find out some things about this version of OpenSSL
+
+ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+echo "$as_me:$LINENO: checking for const input buffers in OpenSSL" >&5
+echo $ECHO_N "checking for const input buffers in OpenSSL... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <openssl/rsa.h>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+ const unsigned char * buf;
+	  unsigned char * outbuf;
+	  RSA rsa;
+
+		RSA_private_decrypt(1,
+							buf,
+							outbuf,
+							&rsa,
+							RSA_PKCS1_PADDING);
+
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+	cat >>confdefs.h <<\_ACEOF
+#define XSEC_OPENSSL_CONST_BUFFERS 1
+_ACEOF
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
+echo "$as_me:$LINENO: checking whether EVP_aes_128_cbc is declared" >&5
+echo $ECHO_N "checking whether EVP_aes_128_cbc is declared... $ECHO_C" >&6
+if test "${ac_cv_have_decl_EVP_aes_128_cbc+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <openssl/evp.h>
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+#ifndef EVP_aes_128_cbc
+  char *p = (char *) EVP_aes_128_cbc;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_have_decl_EVP_aes_128_cbc=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_have_decl_EVP_aes_128_cbc=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_decl_EVP_aes_128_cbc" >&5
+echo "${ECHO_T}$ac_cv_have_decl_EVP_aes_128_cbc" >&6
+if test $ac_cv_have_decl_EVP_aes_128_cbc = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define XSEC_OPENSSL_HAVE_AES 1
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+echo "$as_me:$LINENO: checking whether EVP_CIPHER_CTX_set_padding(NULL,0) is declared" >&5
+echo $ECHO_N "checking whether EVP_CIPHER_CTX_set_padding(NULL,0) is declared... $ECHO_C" >&6
+if test "${ac_cv_have_decl_EVP_CIPHER_CTX_set_padding_NULL_0_+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <openssl/evp.h>
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+#ifndef EVP_CIPHER_CTX_set_padding(NULL,0)
+  char *p = (char *) EVP_CIPHER_CTX_set_padding(NULL,0);
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_have_decl_EVP_CIPHER_CTX_set_padding_NULL_0_=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_have_decl_EVP_CIPHER_CTX_set_padding_NULL_0_=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_decl_EVP_CIPHER_CTX_set_padding_NULL_0_" >&5
+echo "${ECHO_T}$ac_cv_have_decl_EVP_CIPHER_CTX_set_padding_NULL_0_" >&6
+if test $ac_cv_have_decl_EVP_CIPHER_CTX_set_padding_NULL_0_ = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define XSEC_OPENSSL_CANSET_PADDING 1
+_ACEOF
+
+fi
+
+
 
 # Build the object file lists necessary to link the library
 # At the same time, build the include list
