Updates to link against openssl-0.9.8-dev snapshot 20050217
git-svn-id: https://svn.apache.org/repos/asf/xml/security/trunk@351231 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/c/src/configure b/c/src/configure
--- a/c/src/configure
+++ b/c/src/configure
@@ -4059,7 +4059,7 @@ case "${host}" in
 						CC1="${CXX} ${CXXFLAGS} ${PLATFORM_OPTIONS}"
 						CC4="${CC} ${CXXFLAGS} ${PLATFORM_OPTIONS}"
 						MAKE_SHARED="${CXX} ${CXXFLAGS} -Wl,-soname,\$(LIBNAME) -DLINUX -shared ${PIC}"
-						LINK="${CXX} ${CXXFLAGS} -DLINUX ${PIC}"
+						LINK="${CXX} ${CXXFLAGS} -DLINUX -ldl ${PIC}"
 						LINK_COMMAND_1="(cd \$(LIB_DIR) ; rm -f \$(LIBMAJORNAME) ; \$(LN_S) \$(LIBNAME) \$(LIBMAJORNAME))"
 						LINK_COMMAND_2="(cd \$(LIB_DIR) ; rm -f \$(LIBSHORTNAME) ; \$(LN_S) \$(LIBNAME) \$(LIBSHORTNAME))"
 						INSTALL_COMMAND_1="\$(INSTALL) \${THISLIB} \${libdir}"
@@ -5320,6 +5320,60 @@ _ACEOF
 fi
 
 
+echo "$as_me:$LINENO: checking for const input buffer in loadX509Base64Bin" >&5
+echo $ECHO_N "checking for const input buffer in loadX509Base64Bin... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <openssl/x509.h>
+int
+main ()
+{
+ const unsigned char * buf;
+	  d2i_X509(NULL, &buf, 1);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+	cat >>confdefs.h <<\_ACEOF
+#define XSEC_OPENSSL_D2IX509_CONST_BUFFER 1
+_ACEOF
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 
 # Build the object file lists necessary to link the library
 # At the same time, build the include list
